# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
    string_res:
      import: "package:string_res/string_res.dart"
      builder_factories:
        - "stringResourceBuilder"
      build_extensions: {".json": [".dart"]}
      auto_apply: root_package
      build_to: source
      defaults:
        generate_for:
          include:
            - lib/**
            - assets/**