# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
    json_widget:
      import: "package:json_widget/json_widget.dart"
      builder_factories:
        - "jsonWidgetBuilder"
      build_extensions: {".json": [".dart"]}
      auto_apply: root_package
      build_to: cache
      defaults:
        generate_for:
          include:
            - lib/**