name: string_res
description: A Dart Builder for creating a class with String constants from a JSON file.
version: 1.2.1
homepage: https://github.com/maks/string_res

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  build: ^1.2.2
  build_config: ^0.4.0
  dart_style: ^1.3.3
  glob: ^1.2.0
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.9.0
  test:
