name: string_res
description: A generator of strings constants from json
version: 1.2.0
homepage: https://github.com/maks/string_res
author: Maksim Lin <maks@manichord.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  build: ^1.1.4
  build_config: ^0.4.0
  dart_style: ^1.2.8

dev_dependencies:
  pedantic: ^1.9.0
  test: 
